/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String ar = "assets/translations/ar.json";
  static const String en = "assets/translations/en.json";
  static const String logo = "assets/images/logo.png";
  static const String logo0 = "assets/images/logo0.png";
}
